// Generated by gencpp from file rosmod/Empty.msg
// DO NOT EDIT!


#ifndef ROSMOD_MESSAGE_EMPTY_H
#define ROSMOD_MESSAGE_EMPTY_H

#include <ros/service_traits.h>


#include <rosmod/EmptyRequest.h>
#include <rosmod/EmptyResponse.h>


namespace rosmod
{

struct Empty
{

typedef EmptyRequest Request;
typedef EmptyResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Empty
} // namespace rosmod


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rosmod::Empty > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::rosmod::Empty&) { return value(); }
};

template<>
struct DataType< ::rosmod::Empty > {
  static const char* value()
  {
    return "rosmod/Empty";
  }

  static const char* value(const ::rosmod::Empty&) { return value(); }
};


// service_traits::MD5Sum< ::rosmod::EmptyRequest> should match 
// service_traits::MD5Sum< ::rosmod::Empty > 
template<>
struct MD5Sum< ::rosmod::EmptyRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rosmod::Empty >::value();
  }
  static const char* value(const ::rosmod::EmptyRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosmod::EmptyRequest> should match 
// service_traits::DataType< ::rosmod::Empty > 
template<>
struct DataType< ::rosmod::EmptyRequest>
{
  static const char* value()
  {
    return DataType< ::rosmod::Empty >::value();
  }
  static const char* value(const ::rosmod::EmptyRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rosmod::EmptyResponse> should match 
// service_traits::MD5Sum< ::rosmod::Empty > 
template<>
struct MD5Sum< ::rosmod::EmptyResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rosmod::Empty >::value();
  }
  static const char* value(const ::rosmod::EmptyResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosmod::EmptyResponse> should match 
// service_traits::DataType< ::rosmod::Empty > 
template<>
struct DataType< ::rosmod::EmptyResponse>
{
  static const char* value()
  {
    return DataType< ::rosmod::Empty >::value();
  }
  static const char* value(const ::rosmod::EmptyResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROSMOD_MESSAGE_EMPTY_H
