// Generated by gencpp from file rosmod/GetLoggersRequest.msg
// DO NOT EDIT!


#ifndef ROSMOD_MESSAGE_GETLOGGERSREQUEST_H
#define ROSMOD_MESSAGE_GETLOGGERSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rosmod
{
template <class ContainerAllocator>
struct GetLoggersRequest_
{
  typedef GetLoggersRequest_<ContainerAllocator> Type;

  GetLoggersRequest_()
    {
    }
  GetLoggersRequest_(const ContainerAllocator& _alloc)
    {
    }






  typedef boost::shared_ptr< ::rosmod::GetLoggersRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rosmod::GetLoggersRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetLoggersRequest_

typedef ::rosmod::GetLoggersRequest_<std::allocator<void> > GetLoggersRequest;

typedef boost::shared_ptr< ::rosmod::GetLoggersRequest > GetLoggersRequestPtr;
typedef boost::shared_ptr< ::rosmod::GetLoggersRequest const> GetLoggersRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rosmod::GetLoggersRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rosmod::GetLoggersRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rosmod

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'rosmod': ['/home/jeb/Repositories/rosmod/comm/src/rosmod/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rosmod::GetLoggersRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rosmod::GetLoggersRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosmod::GetLoggersRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosmod::GetLoggersRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosmod::GetLoggersRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosmod::GetLoggersRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rosmod::GetLoggersRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::rosmod::GetLoggersRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::rosmod::GetLoggersRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rosmod/GetLoggersRequest";
  }

  static const char* value(const ::rosmod::GetLoggersRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rosmod::GetLoggersRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::rosmod::GetLoggersRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rosmod::GetLoggersRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct GetLoggersRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rosmod::GetLoggersRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::rosmod::GetLoggersRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // ROSMOD_MESSAGE_GETLOGGERSREQUEST_H
