// Generated by gencpp from file three_component_example/ComponentService.msg
// DO NOT EDIT!


#ifndef THREE_COMPONENT_EXAMPLE_MESSAGE_COMPONENTSERVICE_H
#define THREE_COMPONENT_EXAMPLE_MESSAGE_COMPONENTSERVICE_H

#include <ros/service_traits.h>


#include <three_component_example/ComponentServiceRequest.h>
#include <three_component_example/ComponentServiceResponse.h>


namespace three_component_example
{

struct ComponentService
{

typedef ComponentServiceRequest Request;
typedef ComponentServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ComponentService
} // namespace three_component_example


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::three_component_example::ComponentService > {
  static const char* value()
  {
    return "bc470ca3ad39af1aebdc8e6af0a31999";
  }

  static const char* value(const ::three_component_example::ComponentService&) { return value(); }
};

template<>
struct DataType< ::three_component_example::ComponentService > {
  static const char* value()
  {
    return "three_component_example/ComponentService";
  }

  static const char* value(const ::three_component_example::ComponentService&) { return value(); }
};


// service_traits::MD5Sum< ::three_component_example::ComponentServiceRequest> should match 
// service_traits::MD5Sum< ::three_component_example::ComponentService > 
template<>
struct MD5Sum< ::three_component_example::ComponentServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::three_component_example::ComponentService >::value();
  }
  static const char* value(const ::three_component_example::ComponentServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::three_component_example::ComponentServiceRequest> should match 
// service_traits::DataType< ::three_component_example::ComponentService > 
template<>
struct DataType< ::three_component_example::ComponentServiceRequest>
{
  static const char* value()
  {
    return DataType< ::three_component_example::ComponentService >::value();
  }
  static const char* value(const ::three_component_example::ComponentServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::three_component_example::ComponentServiceResponse> should match 
// service_traits::MD5Sum< ::three_component_example::ComponentService > 
template<>
struct MD5Sum< ::three_component_example::ComponentServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::three_component_example::ComponentService >::value();
  }
  static const char* value(const ::three_component_example::ComponentServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::three_component_example::ComponentServiceResponse> should match 
// service_traits::DataType< ::three_component_example::ComponentService > 
template<>
struct DataType< ::three_component_example::ComponentServiceResponse>
{
  static const char* value()
  {
    return DataType< ::three_component_example::ComponentService >::value();
  }
  static const char* value(const ::three_component_example::ComponentServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // THREE_COMPONENT_EXAMPLE_MESSAGE_COMPONENTSERVICE_H
